[project]
site_name = "Test custom javascript with instant navigation"
site_url = "https://test-zensical-custom-js.pages.dev/"  # this causes the problem

nav = [
  {"Home" = "index.md"},
  {"Map" = "map.md"},
  {"Map2" = "map2.md"},
]

# extra_css = [
#  "stylesheets/leaflet.css",
#  "stylesheets/maps.css"
#]

[project.theme]
custom_dir = "docs/overrides"
features = [
    "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.indexes",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "navigation.instant",
]



# -----------------------------------------------------
# custom config variables
# -----------------------------------------------------
[[project.extra_javascript]]
path = "javascripts/subscribe_maps_interval_await.js"
defer = true

# Use with subscribe_maps_interval_await.js
[[project.extra.maps_javascript]]
path = "javascripts/leaflet.js"

# Use with subscribe_maps_interval_await.js
[[project.extra.maps_javascript]]
path = "javascripts/show_map_routes.js"

# TODO These CSS files should be merged, no need to make 2 requests
[[project.extra.maps_css]]
path = "stylesheets/leaflet.css"

[[project.extra.maps_css]]
path = "stylesheets/maps.css"
